package backend;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.DriverManager;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;

class MigracaoCatalogoTest {

    @Test
    void adicionaOsNovosCamposEmUmaBaseLegadaSemAlterarOLivroExistente() throws Exception {
        String url = "jdbc:h2:mem:catalogo_legado_teste;DB_CLOSE_DELAY=-1";
        try (var conexao = DriverManager.getConnection(url, "sa", ""); var comando = conexao.createStatement()) {
            comando.execute("""
                    CREATE TABLE livros (
                        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        isbn VARCHAR(255) NOT NULL UNIQUE,
                        titulo VARCHAR(255) NOT NULL,
                        descricao VARCHAR(5000) NOT NULL,
                        categoria_id INTEGER,
                        autor_id INTEGER,
                        data_publicacao DATE NOT NULL
                    )
                    """);
            comando.execute("""
                    INSERT INTO livros (isbn, titulo, descricao, data_publicacao)
                    VALUES ('9780000000099', 'Livro legado', 'Registro criado antes da migração', DATE '2020-01-01')
                    """);
        }

        Flyway.configure()
                .dataSource(url, "sa", "")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .locations("classpath:db/migration")
                .load()
                .migrate();

        try (var conexao = DriverManager.getConnection(url, "sa", "");
                var consulta = conexao.createStatement();
                var resultado = consulta.executeQuery("SELECT titulo, status, destaque, criado_em, atualizado_em FROM livros")) {
            assertThat(resultado.next()).isTrue();
            assertThat(resultado.getString("titulo")).isEqualTo("Livro legado");
            assertThat(resultado.getString("status")).isEqualTo("PUBLICADO");
            assertThat(resultado.getBoolean("destaque")).isFalse();
            assertThat(resultado.getTimestamp("criado_em")).isNotNull();
            assertThat(resultado.getTimestamp("atualizado_em")).isNotNull();
        }
    }
}
