-- Estrutura mínima para uma instalação nova. Em bases existentes, o Flyway
-- registra a linha de base e aplica apenas os campos novos abaixo.
CREATE TABLE IF NOT EXISTS autores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    biografia VARCHAR(5000),
    data_nascimento DATE NOT NULL,
    nacionalidade VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS livros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    titulo VARCHAR(255) NOT NULL,
    descricao VARCHAR(5000) NOT NULL,
    categoria_id INTEGER,
    autor_id INTEGER,
    data_publicacao DATE NOT NULL
);

ALTER TABLE livros ADD COLUMN IF NOT EXISTS capa_url VARCHAR(2048);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS numero_paginas INTEGER;
ALTER TABLE livros ADD COLUMN IF NOT EXISTS idioma VARCHAR(100);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS editora VARCHAR(255);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS edicao VARCHAR(100);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS classificacao_etaria VARCHAR(20);
ALTER TABLE livros ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'PUBLICADO';
ALTER TABLE livros ADD COLUMN IF NOT EXISTS destaque BOOLEAN DEFAULT FALSE;
ALTER TABLE livros ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE livros ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Livros já cadastrados continuam visíveis no catálogo novo.
UPDATE livros SET status = 'PUBLICADO' WHERE status IS NULL;
UPDATE livros SET destaque = FALSE WHERE destaque IS NULL;
UPDATE livros SET criado_em = CURRENT_TIMESTAMP WHERE criado_em IS NULL;
UPDATE livros SET atualizado_em = CURRENT_TIMESTAMP WHERE atualizado_em IS NULL;
