-- Segurança e dados de perfil. A criação da tabela também cobre instalações novas,
-- pois a versão inicial do projeto deixava a tabela usuarios a cargo do Hibernate.
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    sexo VARCHAR(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    matricula INTEGER NOT NULL
);

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS senha_hash VARCHAR(100);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS papel VARCHAR(30) DEFAULT 'USUARIO';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS imagem_perfil_url VARCHAR(2048);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS ultimo_acesso_em TIMESTAMP;

-- Usuários de instalações antigas permanecem preservados. Eles podem criar uma
-- conta com e-mail e senha para passar a utilizar a autenticação.
UPDATE usuarios SET email = CONCAT('legado-', id, '@bookverse.local') WHERE email IS NULL;
UPDATE usuarios SET papel = 'USUARIO' WHERE papel IS NULL;
UPDATE usuarios SET ativo = TRUE WHERE ativo IS NULL;
UPDATE usuarios SET criado_em = CURRENT_TIMESTAMP WHERE criado_em IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_usuarios_email ON usuarios(email);
