-- A entidade de empréstimos já faz parte do domínio e era criada pelo Hibernate
-- apenas no ambiente local. Em produção, o Flyway passa a controlar sua tabela.
CREATE TABLE IF NOT EXISTS emprestimos (
    id_do_emprestimo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_do_usuario INTEGER NOT NULL,
    isbn_do_livro INTEGER NOT NULL,
    devolvido BOOLEAN NOT NULL
);
